name: Trigger auto deployment for sumith-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sumith-test-app-AutoDeployTrigger-c0060d98-956f-4289-a633-c159ca621d3f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: smlabcontainerregistry.azurecr.io
          username: ${{ secrets.SUMITHTESTAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SUMITHTESTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smlabcontainerregistry.azurecr.io/sumith-test-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SUMITHTESTAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sumith-test-app -g DefaultResourceGroup-CUS --server smlabcontainerregistry.azurecr.io --username  ${{ secrets.SUMITHTESTAPP_REGISTRY_USERNAME }} --password ${{ secrets.SUMITHTESTAPP_REGISTRY_PASSWORD }}
            az containerapp update -n sumith-test-app -g DefaultResourceGroup-CUS --image smlabcontainerregistry.azurecr.io/sumith-test-app:${{ github.sha }}
